using System.Collections.Generic;
using KnightsOfLaCampus.Source.GridNew;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace KnightsOfLaCampus.Units
{
    internal abstract class Unit
    {
        // The current position of the Unit
        public Vector2 mPosition;

        // The current direction (or velocity) of the Unit to draw the animations later 
        // depending on the direction
        public Vector2 mDirection;

        // The Unit is either moveable by the player or has a pre defined path
        public bool mMoveableByPlayer;

        // The path, that the unit is supposed to walk 
        // For "moveable by player" units the path is generated by the player input 
        // For "non moveable by player"- units (=enemy units) the path is already given.
        public Stack<GridNode> mPath;


        public int mHpBar;
        public bool mAlive;

        /// <summary>
        /// Constructor 1
        /// </summary>
        protected Unit()
        {
            // Inits the direction with 0
            mDirection = Vector2.Zero;
        }

        public abstract void AudioUpdate();
        public abstract void GraphicsUpdate();
        public abstract void Update(GameTime gameTime);
        public abstract void Draw(SpriteBatch spriteBatch);

        public void TakeDmg(int damage)
        {
            mHpBar -= damage;
            if (mHpBar <= 0)
            {
                mAlive = false;
            }
        }
    }
}
